from app.models.zone import ZoneSeed


SEEDED_ZONES: list[ZoneSeed] = [
    ZoneSeed(
        id="gabes_north_red",
        label="Ghannouch North Drift",
        center_lat=33.975,
        center_lon=10.155,
        depth_m=16,
        pollution_risk=0.92,
        legal_status="RESTRICTED",
        fleet_load=0.2,
        chlorophyll=0.44,
        wave_height=1.1,
        current_speed=0.65,
        recommended_species=["sardine"],
    ),
    ZoneSeed(
        id="zarrat_c3",
        label="Zone C3 Zarrat",
        center_lat=33.703,
        center_lon=10.558,
        depth_m=22,
        pollution_risk=0.18,
        legal_status="OPEN",
        fleet_load=0.24,
        chlorophyll=0.79,
        wave_height=0.8,
        current_speed=0.38,
        recommended_species=["poulpe", "rouget"],
    ),
    ZoneSeed(
        id="zarrat_south_green",
        label="Zarrat South Shelf",
        center_lat=33.621,
        center_lon=10.533,
        depth_m=19,
        pollution_risk=0.12,
        legal_status="OPEN",
        fleet_load=0.31,
        chlorophyll=0.73,
        wave_height=0.9,
        current_speed=0.41,
        recommended_species=["crevette_royale", "rouget"],
    ),
    ZoneSeed(
        id="mareth_orange",
        label="Mareth Outer Lane",
        center_lat=33.590,
        center_lon=10.395,
        depth_m=14,
        pollution_risk=0.27,
        legal_status="OPEN",
        fleet_load=0.56,
        chlorophyll=0.6,
        wave_height=1.25,
        current_speed=0.33,
        recommended_species=["sardine", "rouget"],
    ),
    ZoneSeed(
        id="protected_black",
        label="Nursery Protection Belt",
        center_lat=33.824,
        center_lon=10.342,
        depth_m=11,
        pollution_risk=0.21,
        legal_status="PROTECTED",
        fleet_load=0.0,
        chlorophyll=0.66,
        wave_height=0.85,
        current_speed=0.22,
        recommended_species=[],
    ),
    ZoneSeed(
        id="akarit_green",
        label="Akarit Productive Edge",
        center_lat=33.982,
        center_lon=10.082,
        depth_m=25,
        pollution_risk=0.15,
        legal_status="OPEN",
        fleet_load=0.12,
        chlorophyll=0.82,
        wave_height=0.72,
        current_speed=0.29,
        recommended_species=["crevette_royale", "poulpe"],
    ),
]

