export type UiLanguage = "fr" | "en" | "tn";

export const uiCopy = {
  tn: {
    langLabel: "اللغة",
    online: "مربوط مباشر",
    offline: "خدمة بلا إنترنت",
    gpsLive: "موقع مباشر",
    gpsCached: "آخر موقع",
    adminAccess: "دخول أدمن",
    pendingSafety: (count: number) => `${count} عمليات سلامة تستنى`,
    shellTitle: "قرر فيسع، أخرج متهني، وإستعمل التطبيق حتى بلاش ريزو.",
    shellBody: "الخريطة، البلاصة المنصوحة، الطريق، وسلامتك في واجهة واضحة للبحارة.",
    departure: "خروج",
    mode: "وضعية",
    safety: "سلامة",
    port: "ميناء",
    liveData: "معلومات مباشرة",
    offlineCache: "مخزن بلاش نت",
    ready: "حاضر",
    emergency: "حالة استعجالية",
    nav: {
      heatmap: ["الخريطة", "بلاص الحي"],
      route: ["الطريق", "ثنية مريحة"],
      lunar: ["القمرة", "وقت باهي"],
      safety: ["سلامة", "SOS حاضر"],
      profile: ["البروفيل", "الفلوكة"],
      admin: ["أدمن", "المنطقة"],
    },
    auth: {
      loginTitle: "إرجع للوحة المهمة",
      registerTitle: "أعمل بروفيل بحار",
      hero: "واجهة تليفون معمولة للتلوث، القانون، المازوت والريزو الضعيف.",
      login: "دخول",
      register: "تسجيل",
      email: "إيميل",
      password: "كلمة السر",
      fullName: "الإسم الكامل",
      licenseType: "نوع الرخصة",
      homePort: "ميناء الدار",
      boatName: "إسم الفلوكة",
      boatLength: "طول الفلوكة (م)",
      engineHp: "قوة الماكينة",
      fuelCapacity: "سعة المازوت (ل)",
      fuelUse: "إستهلاك المازوت (ل/س)",
      fishingGears: "عدة الصيد",
      targetSpecies: "الحوت المقصود",
      emergencyContactName: "إسم للطوارئ",
      emergencyPhone: "تليفون للطوارئ",
      wait: "إستنى شوية...",
      openBoard: "حل المهمة",
      createProfile: "أعمل بروفيل",
      authError: "ما نجمناش ندخلوك",
      next: "التالي",
      back: "رجوع",
      stepOf: (current: number, total: number) => `المرحلة ${current} من ${total}`,
      howItWorks: {
        title: "كيفاش يخدم السيستيم؟",
        subtitle: "ذكاء اصطناعي في خدمة البحارة",
        inputs: {
          title: "معلومات داخلة",
          body: "ساتليت، طقس، قانون، وقمرة.",
        },
        engine: {
          title: "محرك القرار",
          body: "يحسب أحسن بلاصة وأرخص ثنية.",
        },
        outputs: {
          title: "شنوة يعطيك",
          body: "خريطة ذكية، طريق إقتصادي، وسلامة.",
        },
      },
      impact: {
        title: "التأثير متاعنا",
        subtitle: "نغيروا في مستقبل الصيد",
        cards: [
          { title: "إقتصادي", body: "نقص 20% في المازوت.", icon: "economic" as const },
          { title: "بيئي", body: "نحميو بلايص الحوت الصغير.", icon: "environmental" as const },
          { title: "صحي", body: "حوت نظيف بعيد عالتلوث.", icon: "public_health" as const },
          { title: "منطقي", body: "تنظيم ذكي للبحارة في البحر.", icon: "territorial" as const },
        ],
      },
    },
    heatmap: {
      departureDecision: "قرار الخروج",
      missionSupport: "عون المهمة",
      supportTitle: "نظرة عالميدان",
      missionDetails: "تفاصيل المهمة",
      detailsTitle: "علاش البلاصة هذي بالذات",
      rationale: "أسباب النصيحة",
      alternatives: "بلايص أخرى",
      zoneStack: "قائمة البلايص",
      nextActions: "شنوة تعمل توة",
      openRoute: "إبدأ الطريق",
      safetyCheck: "ثبت السلامة",
      routeBriefing: "شوف الثنية",
      safetyControls: "ثبت السلامة",
      productivity: "الإنتاج",
      salinity: "الملوحة",
      slope: "الميلان",
      readability: "حالة الثنية",
      refreshing: "تحديث المهمة...",
    },
    route: {
      eyebrow: "طريق إقتصادي",
      fuelAware: "ثنية متبعة",
      optimizedLane: "ممر مريكل",
      optimized: "طريق مريكل",
      estimatedFuel: "مازوت مقدر",
      fuelSaved: "مازوت مقتصد",
      depthMin: "أقل غرق",
      depthMax: "أكثر غرق",
      weatherRisk: "خطر الطقس",
      corridor: "ممر المهمة",
    },
    lunar: {
      eyebrow: "جدول القمرة",
      loading: "تحميل القمرة",
      offline: "خدمة بلاش نت",
      rise: "طلوع",
      set: "هبوط",
    },
    safetyPage: {
      eyebrow: "سلامة",
      title: "تحكم الطوارئ",
      departureSafety: "سلامة الخروج",
      gps: "موقع GPS",
      checkin: "آخر تسجيل",
      queue: "عمليات تستنى",
      boatPort: "الفلوكة والميناء",
      blocking: "شنوة حابس الخروج",
      preview: "نظرة عالطوارئ",
      checks: "تثبيتات منصوحة",
      contacts: "نمر الطوارئ",
      reminder: "تذكير ميداني",
      reminderBody: "خلي الباتري، الـ GPS والمخزن حاضرين قبل ما تخرج. كان قص الريزو، العمليات تتسجل وتتبعث وحدها كيف يرجع.",
      noContacts: "حتى نمرة طوارئ ما هي مسجلة في البروفيل.",
      sendCheckIn: "إبعث Check-in",
      triggerSos: "إبعث SOS",
      historyEyebrow: "ذاكرة المهمة",
      historyTitle: "توجيهات قديمة",
    },
    profilePage: {
      satellite: "ساتليت كوبيرنيكوس",
      productivity: "إنتاجية",
      live: "مباشر",
      cached: "مخزن",
      weather: "طقس البحر",
      seaState: "حالة البحر",
      freshness: "حداثة المعلومات",
      transparency: "وضوح القرار",
      traceable: "متبع",
      reports: "بلاغات الميدان",
      fieldIntel: "ذكاء الميدان",
      shared: "مشارك",
      pending: (count: number) => `${count} يستناو`,
      reportsBody: "البحارة ينجموا يبلغوا على نوعية الصيد، التلوث، الخطر، الصيد الممنوع والتيار القوي.",
      catch: "صيد",
      pollution: "تلوث",
      hazard: "خطر",
      current: "تيار",
      illegal: "ممنوع",
    },
    chat: {
      launcher: "عون",
      title: "عون المهمة",
      subtitle: "أجوبة قصيرة من السيستيم",
      placeholder: "أكتب سؤالك هنا...",
      send: "إبعث",
      loading: "العون يحضر في الإجابة...",
      tools: "أدوات مستعملة",
      suggestions: "أسئلة فيسع",
      close: "سكر",
      listen: "إسمع بالعربي",
      stop: "قص الصوت",
    },
  },
  fr: {
    langLabel: "Langue",
    online: "Sync live",
    offline: "Mode hors-ligne",
    gpsLive: "GPS live",
    gpsCached: "Dernier GPS",
    adminAccess: "Accès admin",
    pendingSafety: (count: number) => `${count} action(s) safety en attente`,
    shellTitle: "Décider vite, partir en sécurité, rester utile même sans réseau.",
    shellBody: "Carte, zone conseillée, route, safety et offline dans une interface plus claire pour les pêcheurs.",
    departure: "Départ",
    mode: "Mode",
    safety: "Sécurité",
    port: "Port",
    liveData: "Données live",
    offlineCache: "Cache hors-ligne",
    ready: "Prêt",
    emergency: "Urgence",
    nav: {
      heatmap: ["Carte", "Zones live"],
      route: ["Route", "Trajet sûr"],
      lunar: ["Lune", "Bon moment"],
      safety: ["Safety", "SOS prêt"],
      profile: ["Profil", "Bateau & gear"],
      admin: ["Admin", "Territoire"],
    },
    auth: {
      loginTitle: "Retour au tableau mission",
      registerTitle: "Créer le profil pêcheur",
      hero: "Une interface mobile pensée pour pollution, loi, fuel et réseau faible.",
      login: "Connexion",
      register: "Inscription",
      email: "Email",
      password: "Mot de passe",
      fullName: "Nom complet",
      licenseType: "Type de licence",
      homePort: "Port d'attache",
      boatName: "Nom du bateau",
      boatLength: "Longueur bateau (m)",
      engineHp: "Puissance moteur",
      fuelCapacity: "Capacité fuel (L)",
      fuelUse: "Conso fuel (L/h)",
      fishingGears: "Engins de pêche",
      targetSpecies: "Espèces cibles",
      emergencyContactName: "Nom contact urgence",
      emergencyPhone: "Téléphone urgence",
      wait: "Patiente...",
      openBoard: "Ouvrir la mission",
      createProfile: "Créer le profil",
      authError: "Connexion impossible",
      next: "Suivant",
      back: "Retour",
      stepOf: (current: number, total: number) => `Étape ${current} sur ${total}`,
      howItWorks: {
        title: "Comment ça marche ?",
        subtitle: "L'IA au service des pêcheurs",
        inputs: {
          title: "Données entrantes",
          body: "Satellite, météo, lois et cycles lunaires.",
        },
        engine: {
          title: "Moteur de décision",
          body: "Calcul de la meilleure zone et éco-route.",
        },
        outputs: {
          title: "Résultats",
          body: "Heatmap, trajet optimisé et sécurité.",
        },
      },
      impact: {
        title: "Notre impact",
        subtitle: "Changer le futur de la pêche",
        cards: [
          { title: "Économique", body: "-20% de fuel économisé.", icon: "economic" as const },
          { title: "Environnement", body: "Protection des zones sensibles.", icon: "environmental" as const },
          { title: "Santé", body: "Éviter les zones polluées.", icon: "public_health" as const },
          { title: "Territoire", body: "Gestion intelligente de la flotte.", icon: "territorial" as const },
        ],
      },
    },
    heatmap: {
      departureDecision: "Décision départ",
      missionSupport: "Aide mission",
      supportTitle: "Vue rapide terrain",
      missionDetails: "Détails mission",
      detailsTitle: "Pourquoi cette zone et pas une autre",
      rationale: "Raisons de la recommandation",
      alternatives: "Zones alternatives",
      zoneStack: "Pile des zones",
      nextActions: "Actions suivantes",
      openRoute: "إبدأ الطريق",
      safetyCheck: "شوف السلامة",
      routeBriefing: "شوف الطريق",
      safetyControls: "شوف السلامة",
      productivity: "Productivité",
      salinity: "Salinité",
      slope: "Pente",
      readability: "État route",
      refreshing: "Actualisation mission...",
    },
    route: {
      eyebrow: "Éco-route",
      fuelAware: "Route suivie",
      optimizedLane: "couloir optimisé",
      optimized: "Route optimisée",
      estimatedFuel: "Fuel estimé",
      fuelSaved: "Fuel économisé",
      depthMin: "Profondeur min",
      depthMax: "Profondeur max",
      weatherRisk: "Risque météo",
      corridor: "couloir mission",
    },
    lunar: {
      eyebrow: "Tableau lunaire",
      loading: "Chargement lune",
      offline: "Logique offline",
      rise: "Lever",
      set: "Coucher",
    },
    safetyPage: {
      eyebrow: "Sécurité",
      title: "Contrôle d'urgence",
      departureSafety: "Sécurité départ",
      gps: "Position GPS",
      checkin: "Dernier check-in",
      queue: "File hors-ligne",
      boatPort: "Bateau et port",
      blocking: "Ce qui bloque le départ",
      preview: "Prévisualisation urgence",
      checks: "Vérifications recommandées",
      contacts: "Contacts d'urgence",
      reminder: "Rappel terrain",
      reminderBody: "Garde batterie, GPS et cache offline prêts avant départ. Si le signal tombe, la queue sécurité garde l'action pour retry.",
      noContacts: "Aucun contact d'urgence n'est encore enregistré dans le profil.",
      sendCheckIn: "إبعث Check-in",
      triggerSos: "إبعث SOS",
      historyEyebrow: "Mémoire mission",
      historyTitle: "Guidage récent",
    },
    profilePage: {
      satellite: "Satellite Copernicus",
      productivity: "productivité",
      live: "Live",
      cached: "Cache",
      weather: "Météo marine",
      seaState: "état de mer",
      freshness: "Fraîcheur des sources",
      transparency: "Transparence décision",
      traceable: "Traçable",
      reports: "Signalements terrain",
      fieldIntel: "Intelligence terrain",
      shared: "Partagé",
      pending: (count: number) => `${count} en attente`,
      reportsBody: "Les pêcheurs peuvent signaler qualité de capture, pollution, danger, activité illégale et courant fort depuis la zone.",
      catch: "Capture",
      pollution: "Pollution",
      hazard: "Danger",
      current: "Courant",
      illegal: "Illégal",
    },
    chat: {
      launcher: "Assistant",
      title: "Assistant mission",
      subtitle: "Réponses courtes basées sur les données backend",
      placeholder: "Écris ta question ici...",
      send: "Envoyer",
      loading: "L'assistant prépare la réponse...",
      tools: "Outils utilisés",
      suggestions: "Questions rapides",
      close: "Fermer",
      listen: "اسمع بالعربي",
      stop: "وقف الصوت",
    },
  },
  en: {
    langLabel: "Language",
    online: "Live sync",
    offline: "Offline mode",
    gpsLive: "GPS live",
    gpsCached: "Last GPS",
    adminAccess: "Admin access",
    pendingSafety: (count: number) => `${count} safety action(s) pending`,
    shellTitle: "Decide fast, depart safely, stay useful even when the signal drops.",
    shellBody: "Map, best zone, route, safety, and offline resilience in a clearer field interface.",
    departure: "Departure",
    mode: "Mode",
    safety: "Safety",
    port: "Port",
    liveData: "Live data",
    offlineCache: "Offline cache",
    ready: "Ready",
    emergency: "Emergency",
    nav: {
      heatmap: ["Heatmap", "Live zones"],
      route: ["Route", "Safe path"],
      lunar: ["Moon", "Best timing"],
      safety: ["Safety", "SOS ready"],
      profile: ["Profile", "Boat & gear"],
      admin: ["Admin", "Territory"],
    },
    auth: {
      loginTitle: "Return to your mission board",
      registerTitle: "Create your fishing profile",
      hero: "A mobile-first interface built for pollution, legal pressure, fuel, and weak connectivity.",
      login: "Login",
      register: "Register",
      email: "Email",
      password: "Password",
      fullName: "Full name",
      licenseType: "License type",
      homePort: "Home port",
      boatName: "Boat name",
      boatLength: "Boat length (m)",
      engineHp: "Engine HP",
      fuelCapacity: "Fuel capacity (L)",
      fuelUse: "Fuel consumption (L/h)",
      fishingGears: "Fishing gears",
      targetSpecies: "Target species",
      emergencyContactName: "Emergency contact name",
      emergencyPhone: "Emergency phone",
      wait: "Please wait...",
      openBoard: "Open mission board",
      createProfile: "Create profile",
      authError: "Unable to authenticate",
      next: "Next",
      back: "Back",
      stepOf: (current: number, total: number) => `Step ${current} of ${total}`,
      howItWorks: {
        title: "How it works?",
        subtitle: "Multimodal AI for the fisherman",
        inputs: {
          title: "Inputs",
          body: "Satellite, weather, laws, and lunar cycles.",
        },
        engine: {
          title: "Engine",
          body: "Calculates the best zone and eco-route.",
        },
        outputs: {
          title: "Outputs",
          body: "Smart heatmap, route, and safety.",
        },
      },
      impact: {
        title: "Our Impact",
        subtitle: "Changing the future of fishing",
        cards: [
          { title: "Economic", body: "-20% fuel saved.", icon: "economic" as const },
          { title: "Environmental", body: "Protecting sensitive zones.", icon: "environmental" as const },
          { title: "Public Health", body: "Avoiding toxic catch.", icon: "public_health" as const },
          { title: "Territorial", body: "Smart fleet management.", icon: "territorial" as const },
        ],
      },
    },
    heatmap: {
      departureDecision: "Departure decision",
      missionSupport: "Mission support",
      supportTitle: "Quick operating picture",
      missionDetails: "Mission details",
      detailsTitle: "Why this zone and not the others",
      rationale: "Recommendation rationale",
      alternatives: "Alternative zones",
      zoneStack: "Zone stack",
      nextActions: "Next actions",
      openRoute: "Open route",
      safetyCheck: "Open safety",
      routeBriefing: "Open route briefing",
      safetyControls: "Review safety controls",
      productivity: "Productivity",
      salinity: "Salinity",
      slope: "Slope",
      readability: "Route state",
      refreshing: "Refreshing mission...",
    },
    route: {
      eyebrow: "Eco-route",
      fuelAware: "Fuel aware",
      optimizedLane: "optimized lane",
      optimized: "Optimized route",
      estimatedFuel: "Estimated fuel",
      fuelSaved: "Fuel saved",
      depthMin: "Depth min",
      depthMax: "Depth max",
      weatherRisk: "Weather risk",
      corridor: "mission corridor",
    },
    lunar: {
      eyebrow: "Lunar dashboard",
      loading: "Loading moon state",
      offline: "Offline logic",
      rise: "Rise",
      set: "Set",
    },
    safetyPage: {
      eyebrow: "Safety",
      title: "Emergency control",
      departureSafety: "Departure safety",
      gps: "GPS position",
      checkin: "Last check-in",
      queue: "Offline queue",
      boatPort: "Boat and port",
      blocking: "What is blocking departure",
      preview: "Emergency preview",
      checks: "Recommended checks",
      contacts: "Emergency contacts",
      reminder: "Field reminder",
      reminderBody: "Keep battery, GPS, and offline cache ready before departure. If the signal drops, the safety queue keeps the action for retry.",
      noContacts: "No emergency contact is saved in the profile yet.",
      sendCheckIn: "Send check-in",
      triggerSos: "Trigger SOS",
      historyEyebrow: "Mission memory",
      historyTitle: "Recent guidance",
    },
    profilePage: {
      satellite: "Copernicus satellite",
      productivity: "productivity",
      live: "Live",
      cached: "Cached",
      weather: "Marine weather",
      seaState: "sea state",
      freshness: "Source freshness",
      transparency: "Decision transparency",
      traceable: "Traceable",
      reports: "Community reports",
      fieldIntel: "Field intelligence",
      shared: "Shared",
      pending: (count: number) => `${count} pending`,
      reportsBody: "Fishermen can report catch quality, pollution, hazards, illegal activity, and strong currents from the zone itself.",
      catch: "Catch",
      pollution: "Pollution",
      hazard: "Hazard",
      current: "Current",
      illegal: "Illegal",
    },
    chat: {
      launcher: "Assistant",
      title: "Mission assistant",
      subtitle: "Short answers grounded in backend tools",
      placeholder: "Ask your question...",
      send: "Send",
      loading: "Assistant is preparing the answer...",
      tools: "Tools used",
      suggestions: "Quick prompts",
      close: "Close",
      listen: "Listen in Arabic",
      stop: "Stop audio",
    },
  },
} as const;
